name: Other
description: Other issues or questions about the OpenTelemetry eBPF profiler
labels: ["needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file an issue! Please make sure to fill out the entire form below, providing as much context as you can to help us understand your issue.

        Before filing an issue, please be sure you have searched through [existing issues](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) to see if a similar issue already exists.

  - type: dropdown
    attributes:
      label: Issue type
      description: What type of issue is this?
      options:
        - Question
        - Documentation
        - Build issue
        - Configuration issue
        - Integration issue
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Issue description
      description: Please describe your issue, question, or problem in detail.
    validations:
      required: true

  - type: input
    attributes:
      label: Profiler version
      description: What version are you using? (e.g., `v0.4.0`, commit hash, etc)

  - type: textarea
    attributes:
      label: Environment information
      description: Please provide information about your system environment if relevant.
      value: |
        ## Environment
        OS: (e.g., "Ubuntu 20.04")
        Kernel version: (e.g., "5.15.0-73-generic")
        Architecture: (e.g., "x86_64", "arm64")
        Container runtime: (e.g., "Docker 20.10.17", "containerd 1.6.6", "None")
        Deployment method: (e.g., "Kubernetes", "Docker", "systemd", "binary")

  - type: textarea
    attributes:
      label: Additional context
      description: Any additional information you think may be relevant to this issue.

  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0