name: Performance issue
description: Report performance problems with the OpenTelemetry eBPF profiler
labels: ["performance", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a performance issue! Please make sure to fill out the entire form below, providing as much context as you can to help us understand and reproduce the performance problem.

        Before filing a performance issue, please be sure you have searched through [existing performance issues](https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aperformance) to see if a similar issue already exists.

  - type: textarea
    attributes:
      label: Performance problem description
      description: Please describe the performance issue you're experiencing.
      value: |
        ## Description

        ## Expected performance

        ## Actual performance

        ## Impact
    validations:
      required: true

  - type: input
    attributes:
      label: Profiler version
      description: What version did you use? (e.g., `v0.4.0`, commit hash, etc)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment information
      description: Please provide information about your system environment.
      value: |
        ## Environment
        OS: (e.g., "Ubuntu 20.04")
        Kernel version: (e.g., "5.15.0-73-generic")
        Architecture: (e.g., "x86_64", "arm64")
        CPU: (e.g., "Intel Xeon E5-2686 v4", "AMD EPYC 7571")
        Memory: (e.g., "32GB")
        Container runtime: (e.g., "Docker 20.10.17", "containerd 1.6.6", "None")
        Deployment method: (e.g., "Kubernetes", "Docker", "systemd", "binary")
    validations:
      required: true

  - type: textarea
    attributes:
      label: Workload characteristics
      description: Please describe the workload being profiled and its characteristics.
      value: |
        ## Target application(s)
        - Application type: (e.g., "Java web service", "Python data processing", "C++ game server")
        - Process count: (e.g., "10 processes")
        - Thread count per process: (e.g., "50 threads")
        - CPU usage baseline: (e.g., "30% CPU without profiler")
        - Memory usage baseline: (e.g., "2GB RAM without profiler")
        
        ## Profiling configuration
        - Collection interval: (e.g., "10s")
        - Profiling duration: (e.g., "1 hour")
        - Enabled unwinders: (e.g., "native, java, python")
    validations:
      required: true

  - type: textarea
    attributes:
      label: Performance metrics
      description: Please provide specific performance metrics if available.
      value: |
        ## Resource usage with profiler enabled
        - CPU overhead: (e.g., "5% additional CPU usage")
        - Memory overhead: (e.g., "500MB additional memory usage")
        - Disk I/O: (e.g., "10MB/s writes to output file")
        - Network I/O: (e.g., "1MB/s to OTLP endpoint")
        
        ## Measurements
        - Measurement method: (e.g., "htop", "docker stats", "Prometheus metrics")
        - Measurement duration: (e.g., "10 minutes")
        - Comparison baseline: (e.g., "same workload without profiler")

  - type: textarea
    attributes:
      label: Profiler configuration
      description: Please provide the configuration you are using.
      placeholder: |
        # Example:
        # Command: ./ebpf-profiler --collection-interval=5s --verbose=1
        # Environment variables: OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
      render: shell

  - type: textarea
    attributes:
      label: Log output
      description: |
        Please copy and paste any relevant log output, especially performance-related messages.
      render: shell

  - type: textarea
    attributes:
      label: Additional context
      description: Any additional information you think may be relevant to this performance issue.

  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0